Com 2470
sophiemoustard/compani-outils pull request #100
Opened 2021-11-12 10:50 UTC by KennyCallegari

- [x] J'ai testé sur iphone
- [x] J'ai testé sur android

- [ ] La nouvelle version de l'app est compatible avec l'ancienne version de l'API ? (J'ai teste en me mettant sur
  master en api)
  - Oui parce que
  - Non parce que j'ai besoin des virtuels start/endDatetimeStamp

- [] Je n'envoie pas de nouveau paramètre dans une route
    - Si j'en envoie un nouveau, explication et gestion de la compatibilite:
- [ ] J'attends un nouveau champs en retour de l'api: j'ai géré le cas où il n'y est pas -> je n'ai pas géré ce cas
- ~~[ ] J'appelle une nouvelle route: j'ai géré le cas ou la route n'existe pas.~~
- [x] Je n'ai pas changé de constante

- ~~J'ai ajouté une variable d'environnement :~~
  - ~~[ ] Je l'ai ajouté dans env.dev et env.prod aussi~~
  - ~~[ ] J'ai ajouté un message sur le slite pour que la personne qui fait la MEP vérifie que son env.prod est à jour~~

- Cas d'usage :
Je peux changer la date sur la page de modification d'une intervention si celle ci n'est ni horodatée ni facturée.
⚠️ Le comportement est différent sur android / ios
On ne peut pas encore : modifier l'heure ni enregistrer les modifications, ce sera fait dans une prochaine PR

2021-11-12 11:59 UTC, KennyCallegari commented on src/components/TimeStampingCell/index.tsx
> +          {event.startDateTimeStamp
refacto suite aux changements API

2021-11-12 13:52 UTC, manonpalin commented on src/screens/timeStamping/EventEdition/index.tsx
> +          { !!state.showStartPicker && <DateTimePicker value={state.startDate} mode={state.mode} is24Hour={true}
Ici `state.showStartPicker && ...` ne suffirait pas ?

2021-11-12 13:56 UTC, manonpalin commented
Est-ce qu'il n'y a pas moyen d'écrire les mois en français plutot qu'en anglais?

2021-11-12 14:06 UTC, KennyCallegari commented on src/screens/timeStamping/EventEdition/index.tsx
> +          { !!state.showStartPicker && <DateTimePicker value={state.startDate} mode={state.mode} is24Hour={true}
Malheureusement non, `state.showStartPicker` est considéré comme du texte pour une certaine raison 🤷‍♂️

2021-11-12 14:08 UTC, KennyCallegari commented on src/screens/timeStamping/EventEdition/index.tsx
> +          { !!state.showStartPicker && <DateTimePicker value={state.startDate} mode={state.mode} is24Hour={true}
bien vu !

2021-11-12 14:08 UTC, KennyCallegari commented
> Est-ce qu'il n'y a pas moyen d'écrire les mois en français plutot qu'en anglais?

Il faut changer les paramètres de ton téléphone

2021-11-12 14:08 UTC, manonpalin commented on src/screens/timeStamping/EventEdition/styles.ts
>  });
J'ai un soucis d'affichage sur android, le haut de l'en-tête est coupé
<img width="309" alt="Capture d’écran 2021-11-12 à 15 06 28" src="https://user-images.githubusercontent.com/81675019/141479899-c345bfc9-0f80-415e-8b80-8d928bab7fef.png">

Que penses-tu d'ajouter une petite marge verticale sur la screen?

2021-11-12 14:10 UTC, KennyCallegari commented on src/screens/timeStamping/EventEdition/index.tsx
> +          { !!state.showEndPicker && <DateTimePicker value={state.endDate} mode={state.mode} is24Hour={true}
done

2021-11-12 14:16 UTC, KennyCallegari commented on src/screens/timeStamping/EventEdition/index.tsx
> +        showStartPicker: !!action.payload?.start,
non car `action.payload?.start` peut-être `undefined`

2021-11-12 14:16 UTC, KennyCallegari commented on src/screens/timeStamping/EventEdition/styles.ts
>  });
Quelle est ta config android ?

2021-11-12 15:51 UTC, manonpalin commented on src/screens/timeStamping/EventEdition/styles.ts
>  });
Dans les paramètres systèmes de l'emulateur j'ai ca: 
<img width="292" alt="Capture d’écran 2021-11-12 à 16 48 48" src="https://user-images.githubusercontent.com/81675019/141494889-a16b1136-2149-4b29-a39e-07dd6ba184ff.png">

Et l'écran de l'emulateur fait: 1080x2280 px

2021-11-12 16:53 UTC, KennyCallegari commented on src/screens/timeStamping/EventEdition/styles.ts
>  });
Je n'ai pas le problème, ni sur Iphone 8 / SE 2, ni sur Android Pixel 2 / Nexus, ni sur un custom android avec les même dimension que toi :/ 

Sur Iphone 11 Pro j'ai un soucis sur la taille de la status bar mais le problème est présent sur formation aussi, je pense que le problème est hors-scope

2021-11-12 17:04 UTC, manonpalin commented on src/screens/timeStamping/EventEdition/styles.ts
>  });
Sur mon iPhone je n'ai pas de soucis, je l'ai uniquement sur l'emulateur android. 
Mais tu as raison, je l'ai remonté dans ta PR pcq je m'en suis rendu compte mais c'est hors perimetre ;)

2021-11-12 17:08 UTC, manonpalin approved these changes

2021-11-15 09:23 UTC, sophiemoustard requested changes

2021-11-15 09:23 UTC, sophiemoustard commented on src/components/EventDateTimeDetails/index.tsx
> +  onPress: (mode: ModeType) => void,
je crois qu'une bonne pratique est de definir les parametres obligatoires en premier

2021-11-15 09:23 UTC, sophiemoustard commented on src/components/EventDateTimeDetails/index.tsx
> +  onPress,
idem

2021-11-15 09:32 UTC, sophiemoustard commented on src/components/EventDateTimeDetails/index.tsx
> +const EventDateTimeDetails = ({
je me pose la qustion de l'utilité de `Details` dans le nom du composant (c'est un vraie question !) qu'en penses tu ?

2021-11-15 09:40 UTC, KennyCallegari commented on src/screens/timeStamping/EventEdition/index.tsx
> +interface ActionType {
done

2021-11-15 09:41 UTC, KennyCallegari commented on src/screens/timeStamping/EventEdition/index.tsx
> +        showStartPicker: !!action.payload?.start,
bien vu, done

2021-11-15 09:46 UTC, KennyCallegari commented on src/screens/timeStamping/EventEdition/index.tsx
> +  const isIOS = Platform.OS === 'ios';
ça me va, done

2021-11-15 09:47 UTC, KennyCallegari commented on src/screens/timeStamping/EventEdition/index.tsx
> +          { state.showStartPicker && <DateTimePicker value={state.startDate} mode={state.mode} is24Hour={true}
done

2021-11-15 09:49 UTC, KennyCallegari commented on src/screens/timeStamping/EventEdition/index.tsx
> +          { state.showStartPicker && <DateTimePicker value={state.startDate} mode={state.mode} is24Hour={true}
done

2021-11-15 09:50 UTC, KennyCallegari commented on src/components/EventDateTimeDetails/index.tsx
> +      { !!isTimeStamped && <View style={styles.iconContainer}>
done

2021-11-15 09:55 UTC, KennyCallegari commented on src/screens/timeStamping/EventEdition/index.tsx
> +    case SWITCH_PICKER:
pour moi, le mot toggle c'est pour afficher le composant. Ici je voulais qu'on comprenne que si on en affiche un, l'autre disparait, d'où le mot 'switch'

2021-11-15 09:56 UTC, KennyCallegari commented on src/screens/timeStamping/EventEdition/index.tsx
> +  const initialDate = new Date(event.startDate);
pas vraiment, je l'ai supprimé

2021-11-15 09:57 UTC, KennyCallegari commented on src/screens/timeStamping/EventEdition/index.tsx
> +            display="spinner" onChange={onChangePicker} locale="fr-FR" />}
done

2021-11-15 10:04 UTC, KennyCallegari commented on src/components/EventDateTimeDetails/index.tsx
> +  const displayedTime = formatTime(formattedDate);
Il me semble qu'un composant se render quand ses props changent, ce qui serait identique au comportement avec un useEffect.
Vu que je n'en suis pas sûr, j'ai préféré faire un UseEffect

2021-11-15 10:07 UTC, KennyCallegari commented on src/components/EventDateTimeDetails/styles.ts
> +    borderRightWidth: BORDER_WIDTH / 2,
ça rend le clic sur le composant un peu étrange : sur un côté le clic rend la barre centrale invisible, sur l'autre côté non. C'est pour ça que j'ai préféré couper la barre en deux.
Qu'en penses-tu ?

2021-11-15 10:10 UTC, KennyCallegari commented on src/components/EventDateTimeDetails/index.tsx
> +  onPress: (mode: ModeType) => void,
done

2021-11-15 10:10 UTC, KennyCallegari commented on src/components/EventDateTimeDetails/index.tsx
> +  onPress,
done

2021-11-15 10:28 UTC, KennyCallegari commented on src/components/EventDateTimeDetails/index.tsx
> +const EventDateTimeDetails = ({
Hum 🤔  Je n'ai pas trop d'avis dessus, EventDateTime me va aussi et comme le nom est plus court, on peut le changer !

2021-11-15 14:25 UTC, sophiemoustard commented on src/components/TimeStampingCell/index.tsx
> +  endDateTimeStamp: boolean,
est ce que ces changements sont voulus du coup ?

2021-11-15 14:26 UTC, sophiemoustard commented on src/screens/timeStamping/EventEdition/index.tsx
> +    case SWITCH_PICKER:
ok !

2021-11-15 14:26 UTC, sophiemoustard commented on src/components/EventDateTimeDetails/styles.ts
> +    borderRightWidth: BORDER_WIDTH / 2,
hum je vois ok

2021-11-15 15:00 UTC, KennyCallegari commented on src/components/TimeStampingCell/index.tsx
> +  endDateTimeStamp: boolean,
Oui ! Vu que les virtuals ont le même rôle que ces variables, je me suis dit que ça serait mieux d'homogénéiser le tout

2021-11-15 16:03 UTC, sophiemoustard approved these changes

2021-11-15 16:03 UTC, merged