Com 2541
sophiemoustard/compani-outils pull request #108
Opened 2021-11-25 17:28 UTC by KennyCallegari

- [x] J'ai testé sur iphone
- [x] J'ai testé sur android

- [x] La nouvelle version de l'app est compatible avec l'ancienne version de l'API ? (J'ai teste en me mettant sur
  master en api)

- [x] Je n'envoie pas de nouveau paramètre dans une route
    - Si j'en envoie un nouveau, explication et gestion de la compatibilite:
- ~~[ ] J'attends un nouveau champs en retour de l'api: j'ai géré le cas où il n'y est pas~~
- ~~[ ] J'appelle une nouvelle route: j'ai géré le cas ou la route n'existe pas.~~
- [x] Je n'ai pas changé de constante

- ~~J'ai ajouté une variable d'environnement :~~
  - ~~[ ] Je l'ai ajouté dans env.dev et env.prod aussi~~
  - ~~[ ] J'ai ajouté un message sur le slite pour que la personne qui fait la MEP vérifie que son env.prod est à jour~~

- Cas d'usage :
Refacto de EventEdition : 
  - On ajoute un composant pour regrouper les pickers de début et de fin
  - On gère un state à part dans ce composant
  - on refacto la fonction onLeave (ça marche pas et je comprends pas pourquoi)

2021-11-26 11:30 UTC, manonpalin commented on src/components/EventDateTimeEdition/index.tsx
> +const isIOS = Platform.OS === IOS;
J'ai l'impression que partout où on utilise la constante IOS, on effectue le test `Platform.OS === IOS;` que penses-tu de plutot creer la constante isIOS dans le fichier `constants`?

2021-11-26 11:38 UTC, manonpalin commented on src/screens/timeStamping/EventEdition/index.tsx
> +export interface EventEditionStateType {
Que penses-tu de definir ces types dans le fichier EventType?

2021-11-26 11:41 UTC, manonpalin commented
Pour quelle(s) raison(s) n'as-tu pas créé de composant pour le header?

2021-11-26 12:51 UTC, KennyCallegari commented on src/screens/timeStamping/EventEdition/index.tsx
> +export interface EventEditionStateType {
Ce n'est pas une pratique qu'on a créé encore, ça pourrait faire l'objet d'une veille sur les bonnes pratiques des reducers, qu'en penses-tu ?

2021-11-26 12:55 UTC, KennyCallegari commented on src/components/EventDateTimeEdition/index.tsx
> +const isIOS = Platform.OS === IOS;
done

2021-11-26 13:18 UTC, manonpalin commented on src/screens/timeStamping/EventEdition/index.tsx
> +export interface EventEditionStateType {
J'ai quand meme l'impression qu'on a commencé à le faire pour les types que l'on utilise a plusieurs endroits dans le code, je penses notamment aux fichiers `UserType`, `EventsType`etc ... Je trouve que dans ce cas d'utilisation ca s'y prêtait plutot bien aussi :) 
Si tu penses que ca peut ne pas être une bonne pratique pour les reducers, on peut laisser comme ca et ll'ajouter sur le slite !

2021-11-26 13:33 UTC, KennyCallegari commented on src/screens/timeStamping/EventEdition/index.tsx
> +export interface EventEditionStateType {
Les fichiers de Typages sont utilisés pour les objets récurrents (`user`, `event`, ...). Ici on viendrait séparer les types liés au composant lui-même (donc les types ne seront pas ré-utilisés ailleurs.

Je trouve que ça peut être une bonne pratique car les typages prennent de la place mais il faudrait savoir comment on les place : dans un fichier à part dans le dossier du composant ? Dans un fichier de typage commun aux composants ?
On peut en débattre ici ou bien se renseigner d'abord sur différentes bonnes pratiques.

Personnellement je suis plutôt partant pour faire une veille sur les reducers avant de créer un fichier de typage car je ne suis vraiment pas sûr de quelle forme il pourrait avoir.

Qu'en penses-tu ?

2021-11-26 14:43 UTC, manonpalin commented on src/screens/timeStamping/EventEdition/index.tsx
> +export interface EventEditionStateType {
Hmmmm je vois, en effet, comme ca je n'ai pas la réponse non plus. Je te rejoins sur le fait qu'on puisse se renseigner sur le sujet pour connaître les bonnes pratiques. En attendant de faire ces recherches, laissons comme c'est ici :)

2021-11-26 14:47 UTC, manonpalin approved these changes

2021-11-26 15:44 UTC, sophiemoustard commented on src/components/EventDateTimeEdition/index.tsx
> +    <View>
je pense que tu peux mettre <> non ?

2021-11-26 15:44 UTC, sophiemoustard commented on src/components/EventDateTimeEdition/index.tsx
> +  const [state, dispatch] = useReducer(reducer, initialState);
on pourrait imaginer avoir plusieurs useReducer dans ce fichier. que penses tu de renommer `state` et `dispatch` avec des noms moins génériques ?

2021-11-26 15:44 UTC, sophiemoustard commented on src/screens/timeStamping/EventEdition/index.tsx
> +export interface EventEditionStateType {
par rapport a ces interrogations, je suis d'accord avec le constat de Manon et je pense qu'on peut ameliorer ca
pourquoi pas faire un veille dessus 
une vigilance néanmoins : en faisant on reporte le sujet a plus tard .... et voir a jamais :( 
J'ai l'impression que ce genre de sujet rentre dans la catégorie des bonnes pratiques qui seront bonnes si elles fonctionnent pour nous, si elle est claire et bien définie
il y a un ticket pour l'annulation de l'horodatage dans le sprint je trouverai ca cool que la modif soit faite a ce moment la 
ce qui pousse l'un de vous a faire la veille avant -> dans le cadre de sa veille de la semaine ? ;)
Ce n'est pas obligé d'etre tres long (et ca ne doit pas l'etre haha -> tout le monde a son avis a donner sur les "bonnes pratiques" et ce n'est pas toujours la meme direction qui est prise selon les gens, les projets,,...)

et pour donner mon avis sur ta question kenny " dans un fichier à part dans le dossier du composant ? Dans un fichier de typage commun aux composants ?"
-> je dirais dans le dossier du composant car c'est tres specifique a son fonctionnement interne :)

2021-11-26 15:54 UTC, sophiemoustard commented on src/screens/timeStamping/EventEdition/index.tsx
> +export interface EventEditionStateType {
par rapport a ces interrogations, je suis d'accord avec le constat de Manon et je pense qu'on peut ameliorer ca
pourquoi pas faire un veille dessus 
une vigilance néanmoins : en faisant on reporte le sujet a plus tard .... et voir a jamais :( 
J'ai l'impression que ce genre de sujet rentre dans la catégorie des bonnes pratiques qui seront bonnes si elles fonctionnent pour nous, si elle est claire et bien définie
il y a un ticket pour l'annulation de l'horodatage dans le sprint je trouverai ca cool que la modif soit faite a ce moment la 
ce qui pousse l'un de vous a faire la veille avant -> dans le cadre de sa veille de la semaine ? ;)
Ce n'est pas obligé d'etre tres long (et ca ne doit pas l'etre haha -> tout le monde a son avis a donner sur les "bonnes pratiques" et ce n'est pas toujours la meme direction qui est prise selon les gens, les projets,,...)

et pour donner mon avis sur ta question kenny " dans un fichier à part dans le dossier du composant ? Dans un fichier de typage commun aux composants ?"
-> je dirais dans le dossier du composant car c'est tres specifique a son fonctionnement interne :)

2021-11-26 16:29 UTC, KennyCallegari commented on src/screens/timeStamping/EventEdition/index.tsx
> +export interface EventEditionStateType {
Je suis d'accord !
Je l'ai ajouté dans la description du ticket 2471 sur l'annulation d'un horodatage

2021-11-26 16:45 UTC, KennyCallegari commented on src/components/EventDateTimeEdition/index.tsx
> +  const [state, dispatch] = useReducer(reducer, initialState);
Je ne vois pas comment tu veux découper le reducer en plusieurs reducers ?

Pour state / dispatch, il me semble que notre pratique est d'appeler le reducer lié au composant comme ça (pour ne pas appeler le state de `MonComposant` : `monComposantState`

Comment tu voyais ça ?

2021-11-26 16:46 UTC, KennyCallegari commented on src/components/EventDateTimeEdition/index.tsx
> +    <View>
done

2021-11-29 08:34 UTC, sophiemoustard commented on src/components/EventDateTimeEdition/index.tsx
> +  const [state, dispatch] = useReducer(reducer, initialState);
pardon je me suis mal exprimé : je ne voulais pas decouper ce reducer en plusieurs 
mais typiquement on pourrait en avoir un pour al gestion d'erreur, un pour la gestion de l'edition de la date / heure comme la ; en bref utiliser plusieurs fois `useReducer` : 
```
const [state1, dispatch1] = useReducer(...)
const [state2, dispatch2] = useReducer(...)
```
auquel cas je trouve que ce serait mieux de specifier de quel `state` on parle

également, on pourrait utiliser un `useState` dans ce composant a un moment : la variable ainsi défini fait bien partie de l'état du composant mais ne serait pas pour autant inclu dans la variable `state`. Je trouve du coup ce nommage un peu trop générique

2021-11-29 08:38 UTC, sophiemoustard commented on src/components/EventDateTimeEdition/index.tsx
> +  const [state, dispatch] = useReducer(reducer, initialState);
par exemple : 
- dans `TimeStampingCell` je trouve ca a ssez etrange d'avoir appeler la variable `state` car pour moi l'état du composant (son state) c'est l'ensemble `state` + `modalVisible` + `isEventStarting`
- coté formation, dans `ActivityCell`, on a appelé la variable `colors` ce que je trouve plus specifique et clair. On aurait pu aller plus loin d'ailleurs et appeler `colorDispatch` la 2eme variable

2021-11-29 11:09 UTC, KennyCallegari commented on src/components/EventDateTimeEdition/index.tsx
> +  const [state, dispatch] = useReducer(reducer, initialState);
Pour ce fichier, je ne vois vraiment pas comment on peut appliquer ça, tu parles du fichier EventEdition ?
Pour le state d'erreur, ça sera fait dans une grosse PR de refacto, c'est pour ça que j'ai gardé un useState.

J'ai fait le changement dans EventEdition, dit moi ce que tu en penses

2021-11-29 11:26 UTC, KennyCallegari commented on src/components/EventDateTimeEdition/index.tsx
> +  const [state, dispatch] = useReducer(reducer, initialState);
J'ai refacto TimeStampingCell aussi

2021-11-29 11:30 UTC, KennyCallegari commented on src/components/EventDateTimeEdition/index.tsx
> +  const [state, dispatch] = useReducer(reducer, initialState);
J'ai refacto EventDateTimeEdition aussi

2021-11-29 11:31 UTC, KennyCallegari commented on src/components/EventDateTimeEdition/index.tsx
> +  const [state, dispatch] = useReducer(reducer, initialState);
Il reste authContext (où je trouve que 'state' est approprié) et QRCodeScanner (qui sera refacto avec le reducer pour la gestion d'erreur.

2021-11-29 12:06 UTC, sophiemoustard requested changes

2021-11-29 12:50 UTC, KennyCallegari commented on src/components/modals/ExitModal/styles.ts
> +    maxWidth: 192,
non ce n'est pas normal, bien vu. 
c'est problablement un oubli d'un rebase

2021-11-29 14:15 UTC, KennyCallegari commented on src/screens/timeStamping/EventEdition/index.tsx
> +export const SET_START = 'setStart';
bien vu c'était un oubli, j'ai changé la place de SWITCH_PICKER et HIDE_PICKER

2021-11-29 14:44 UTC, sophiemoustard approved these changes

2021-11-29 14:56 UTC, merged