COM-2521 - display intervenant
sophiemoustard/compani-outils pull request #111
Opened 2021-12-01 11:23 UTC by manonpalin

- [x] J'ai testé sur iphone
- [ ] J'ai testé sur android

- [ ] La nouvelle version de l'app est compatible avec l'ancienne version de l'API ? (J'ai teste en me mettant sur
  master en api)
  - Oui parce que
  - Non parce que

- [x] Je n'envoie pas de nouveau paramètre dans une route
    - Si j'en envoie un nouveau, explication et gestion de la compatibilite:
- [ ] J'attends un nouveau champs en retour de l'api: j'ai géré le cas où il n'y est pas -np
- [ ] J'appelle une nouvelle route: j'ai géré le cas ou la route n'existe pas. -np
- [x] Je n'ai pas changé de constante 

- J'ai ajouté une variable d'environnement : -np
  - [ ] Je l'ai ajouté dans env.dev et env.prod aussi
  - [ ] J'ai ajouté un message sur le slite pour que la personne qui fait la MEP vérifie que son env.prod est à jour

- Cas d'usage : L'intervenant est visible (photo, nom et prénom) sur la page d'édition d'une intervention

2021-12-01 13:21 UTC, cmolle commented on src/core/helpers/utils.ts
> +export const getLastVersion = (versions: any) => {
Que penses-tu de mettre `Array<{ startDate: DateProps }>` comme type ? Ca me semble un bon compromis entre assez generique mais tout de meme restreindre pour verifier que ce qu'on passe a bien ce qu'il faut poru la methode ?

2021-12-01 13:21 UTC, cmolle commented on src/core/helpers/utils.ts
> +};
Qu'est-ce qui te fait destructurer versions[0] dans le premier cas et pas dans le deuxieme ?

2021-12-01 13:21 UTC, cmolle commented on src/screens/timeStamping/EventEdition/index.tsx
> +const formatAuxiliary = (auxiliary: UserType) => ({
Est-ce que ca vaudrait le coup d'installer lodash/pick pour ici ? Ou on se dit qu'on attend de voir si il est utile a plusieurs endroits dans l'app ?

2021-12-01 13:21 UTC, cmolle commented on src/screens/timeStamping/EventEdition/index.tsx
> +    auxiliary: initialAuxiliary,
A-t-on besoin de declarer initialAuxiliary  en dehors de initialState ?

2021-12-01 13:21 UTC, cmolle commented on src/screens/timeStamping/EventEdition/index.tsx
> +        {/* <Text>{activeAuxiliaries.map(aux => aux?.contracts?.endDate)}</Text> */}
Pourquoi est-ce commenté ?

2021-12-01 13:21 UTC, cmolle commented on src/screens/timeStamping/EventEdition/index.tsx
> +  const [source, setSource] = useState<ImageSourcePropType>({});
Que penses-tu plutot de auxiliaryPicture ? Je trouve que source n'est pas tres explicite.

2021-12-01 13:21 UTC, cmolle commented on src/screens/timeStamping/EventEdition/index.tsx
> +          return isBefore(aux?.contracts?.startDate, event.startDate);
Que penses-tu de simplifier en `isBefore(aux?.contracts?.startDate, event.startDate) && (aux.contracts.endDate || isAfter(aux.contracts?.endDate, event.endDate))`

2021-12-01 13:21 UTC, cmolle commented on src/screens/timeStamping/EventEdition/index.tsx
> +          return isBefore(aux?.contracts?.startDate, event.startDate);
A voir aussi si il faut le découper dans une autre méthode.

2021-12-01 13:21 UTC, cmolle commented on src/screens/timeStamping/EventEdition/index.tsx
> +        <View style={isAuxiliaryEditable ? styles.auxiliaryCell : styles.auxiliaryCellNotEditable} >
Qu'est-ce qui ta fait ajoute cette condition dans ce ticket ? On ne peut pas vraiment le tester vu que pour l'instant on ne peut pas avoir les deux etats.

2021-12-01 13:21 UTC, cmolle commented on src/screens/timeStamping/EventEdition/styles.ts
> +    height: 72,
A mettre dans une constante ?

2021-12-01 13:21 UTC, cmolle commented on src/screens/timeStamping/EventEdition/styles.ts
> +    height: 72,
Il y en a plusieurs dans le fichier

2021-12-01 13:26 UTC, cmolle commented on src/screens/timeStamping/EventEdition/index.tsx
> +  const [currentAuxiliary] = useState<AuxiliaryType>(initialAuxiliary);
Comment sera utilise currentAuxiliary dans la suite ? Est-ce une variable similaire a dates ?

2021-12-01 13:42 UTC, cmolle commented on src/screens/timeStamping/EventEdition/index.tsx
> +          { isAuxiliaryEditable &&
un espace en trop

2021-12-01 13:42 UTC, cmolle commented on src/screens/timeStamping/EventEdition/index.tsx
> +        {/* <Text>{activeAuxiliaries.map(aux => aux?.contracts?.endDate)}</Text> */}
Je pense qu'il vaut mieux ne pas laisser cette ligne

2021-12-01 13:44 UTC, sophiemoustard requested changes

2021-12-01 15:49 UTC, manonpalin commented on src/screens/timeStamping/EventEdition/index.tsx
> +    auxiliary: initialAuxiliary,
Non c'est corrigé

2021-12-01 15:51 UTC, manonpalin commented on src/core/helpers/utils.ts
> +export const getLastVersion = (versions: any) => {
Finalement je n'avais pas compris de quoi était composé le tableau contracts, on n'a pas besoin d'utiliser la methode getLastVersion car a seulement besoin des dates startDate et endDate qui se trouvent a la racine de chaqeu objet du tableau contracts

2021-12-01 15:56 UTC, manonpalin commented on src/core/helpers/dates.ts
> +type DateProps = Date | string | null | undefined;
J'avais une erreur es-lint que je n'ai plus apres toutes les modifs qu'on a fait donc je le retire ;)

2021-12-01 15:58 UTC, manonpalin commented on src/screens/timeStamping/EventEdition/index.tsx
> +  const [currentAuxiliary] = useState<AuxiliaryType>(initialAuxiliary);
Oui j'avais fait un mélange étrange. En effet currentAuxiliary était similaire a dates (qui est maintenant devenu event)

2021-12-01 15:59 UTC, manonpalin commented on src/screens/timeStamping/EventEdition/index.tsx
> +  const [source, setSource] = useState<ImageSourcePropType>({});
Oui bien vu !

2021-12-01 16:03 UTC, manonpalin commented on src/screens/timeStamping/EventEdition/index.tsx
> +const formatAuxiliary = (auxiliary: UserType) => ({
Oui c'est une bonne idee, il y a deja un autre endroit ou on peut l'utiliser sur cette page donc je pense qu'on peut l'installer, qu'en penses-tu?

2021-12-01 16:03 UTC, manonpalin commented on src/screens/timeStamping/EventEdition/index.tsx
> +        <View style={isAuxiliaryEditable ? styles.auxiliaryCell : styles.auxiliaryCellNotEditable} >
C'est retiré

2021-12-01 16:51 UTC, cmolle commented on src/screens/timeStamping/EventEdition/index.tsx
> +const formatAuxiliary = (auxiliary: UserType) => ({
Je suis d'accord

2021-12-01 17:14 UTC, cmolle reviewed
J'ai un erreur quand j'essaye de modifier l'heure 🤔 "value.getTime() is not a function"

2021-12-01 17:14 UTC, cmolle commented on src/screens/timeStamping/EventEdition/index.tsx
> +
Est-ce qu'il ne faudrait pas utiliser event.endDate et startDate ? si on change la date de l'evenement, on n'a pas les memes auxiliaires qui sont actives.

2021-12-01 17:25 UTC, sophiemoustard commented on src/screens/timeStamping/EventEdition/index.tsx
> +
je me suis posée la meme question et j'ai un peu eu du mal a trancher... tu as sans doute raison

2021-12-01 17:35 UTC, manonpalin commented on src/screens/timeStamping/EventEdition/index.tsx
> +
Oui tu as raison :)

2021-12-01 17:50 UTC, cmolle commented on src/screens/timeStamping/EventEdition/index.tsx
> +
enfait je pense que dans l'ideal il faudrait regarder si le jour a changé, sinon on fait un appel a chaque fois que la date change ce qui n'est pas tres optimal vu que les contrats s'arretent a la fin d'une journee et commence au debut dune journee. mais on pourra le faire dans une prochaine pr. 

par contre j'avais un comportement bizarre avant tes derniers changements Manon : des appels infini a `/users/sector-histories` + je ne pouvais pas changer les heures. Je ne sais pas exactement a quoi c'est du (et comment ca s'est corrigé) mais je pense que c'est du au fait d'utiliser event ici a la place de initialState et je me demande si ca ne vient pas du fait que initialState est une constante et non un state et donc qu'elle est redefini a chaque rendu.

2021-12-02 08:08 UTC, manonpalin commented on src/components/EventAuxiliaryEdition/styles.ts
> +    marginBottom: MARGIN.SM,
J'ai ajouté cette marge pour que les messages d'erreur ne soient pas collés aux infos de l'intervenant

2021-12-02 08:17 UTC, cmolle approved these changes

2021-12-02 08:17 UTC, sophiemoustard approved these changes

2021-12-02 08:17 UTC, merged