Com 2522
sophiemoustard/compani-outils pull request #112
Opened 2021-12-02 13:09 UTC by manonpalin

- [x] J'ai testé sur iphone
- [ ] J'ai testé sur android

- [ ] La nouvelle version de l'app est compatible avec l'ancienne version de l'API ? (J'ai teste en me mettant sur
  master en api)
  - Oui parce que
  - Non parce que

- [ ] Je n'envoie pas de nouveau paramètre dans une route
    - Si j'en envoie un nouveau, explication et gestion de la compatibilite:
- [ ] J'attends un nouveau champs en retour de l'api: j'ai géré le cas où il n'y est pas
- [ ] J'appelle une nouvelle route: j'ai géré le cas ou la route n'existe pas.
- [ ] Je n'ai pas changé de constante

- J'ai ajouté une variable d'environnement :
  - [ ] Je l'ai ajouté dans env.dev et env.prod aussi
  - [ ] J'ai ajouté un message sur le slite pour que la personne qui fait la MEP vérifie que son env.prod est à jour

- Cas d'usage : Je peux editer l'auxiliaire d'une intervention

2021-12-02 16:21 UTC, sophiemoustard requested changes

2021-12-02 16:21 UTC, sophiemoustard commented on src/components/BottomModal/index.tsx
> +  <Modal visible={visible} onRequestClose={onRequestClose}>
ici tu peux ajouter la props `transparent`

2021-12-02 16:21 UTC, sophiemoustard commented on src/components/BottomModal/styles.ts
> +  modalContainer: {
ici ajouter `backgroundColor: MODAL_BACKDROP_GREY`

2021-12-02 16:21 UTC, sophiemoustard commented on src/components/BottomModal/styles.ts
> +  modalContent: {
et la `backgroundColor: WHITE` pour avoir un style plus proche de la modal (cf ce qui est coté formation

2021-12-02 16:21 UTC, sophiemoustard commented on src/components/EventAuxiliaryEdition/index.tsx
> +        }
ici je pense que tu peux simplifier comme suit
```
{isEditable && <FeatherButton name='chevron-down' onPress={() => setAuxiliaryEditionModal(true)} />}
<NiEventAuxiliaryEditionModal visible={auxiliaryEditionModal} auxiliaryOptions={auxiliaryOptions}
     onRequestClose={() => setAuxiliaryEditionModal(false)} eventEditionDispatch={eventEditionDispatch} />
```

2021-12-02 16:21 UTC, sophiemoustard commented on src/components/EventAuxiliaryEdition/styles.ts
> +    height: 72,
tu pourrais mettre `paddingVertical: PADDING.MD,` plutot
et rassembler tous les padding ensemble

2021-12-02 16:21 UTC, sophiemoustard commented on src/components/EventAuxiliaryEditionModal/index.tsx
> +  auxiliaryOptions: AuxiliaryType [],
tu as une espace en trop avant []

2021-12-02 16:21 UTC, sophiemoustard commented on src/components/EventAuxiliaryEditionModal/index.tsx
> +    <TouchableOpacity onPress={() => onPress(aux)}>
ici tu pourrais ajouter un peu de style pour aerer qu'en penses tu 
```
auxiliaryItem: {
 padding: PADDING.LG,
},
```

2021-12-02 16:21 UTC, sophiemoustard commented on src/components/EventAuxiliaryEditionModal/index.tsx
> +      <FlatList data={auxiliaryOptions} keyExtractor={item => item._id}
et ici tu pourrais ajouter `ItemSeparatorComponent={renderSeparator}` em props
avec `  const renderSeparator = () => <View style={styles.separator} />;`
et pour le style 
```
separator: {
    borderTopWidth: BORDER_WIDTH,
    borderColor: COPPER_GREY[200],
  },
```

2021-12-02 16:21 UTC, sophiemoustard commented on src/components/EventAuxiliaryEditionModal/index.tsx
> +      <Text>{formatIdentity(aux.identity, 'FL')}</Text>
et un peu de style sur le Text 
```
  auxiliaryItemText: {
    ...FIRA_SANS_REGULAR.MD,
  },
```

2021-12-02 16:21 UTC, sophiemoustard commented on src/types/EventType.ts
> +  auxiliary: UserType | AuxiliaryType,
ici on pourrait juste mettre AuxiliaryType non ?

2021-12-02 17:07 UTC, manonpalin commented on src/components/EventAuxiliaryEdition/index.tsx
> +          <NiEventAuxiliaryEditionModal visible={auxiliaryEditionModal} auxiliaryOptions={auxiliaryOptions}
Ok c'est noté :)

2021-12-02 17:12 UTC, manonpalin commented on src/components/BottomModal/styles.ts
> +  modalContainer: {
Je n'ai pas mis `transparent` et `backgroundColor: MODAL_BACKDROP_GREY` car je trouve que ca rend la modale beaucoup moins lisible, qu'en penses-tu?

<img width="330" alt="Capture d’écran 2021-12-02 à 18 10 06" src="https://user-images.githubusercontent.com/81675019/144470099-8f6e990b-9afe-46a2-b912-b3857f61bcdc.png">

2021-12-02 17:16 UTC, manonpalin commented on src/components/EventAuxiliaryEdition/index.tsx
> +        }
Oui bien vu

2021-12-02 17:25 UTC, manonpalin commented on src/components/EventAuxiliaryEditionModal/index.tsx
> +    <TouchableOpacity onPress={() => onPress(aux)}>
Oui bonne idee, je ne pensais pas faire de style pour le faire dans le ticket dedié. Mais dans le cas ou on aurait pas le temps de le faire a ce sprint, il vaut mieux avoir un style tu as raison !

2021-12-02 17:34 UTC, manonpalin commented on src/types/EventType.ts
> +  auxiliary: UserType | AuxiliaryType,
Oui bien vu !

2021-12-02 17:55 UTC, sophiemoustard requested changes

2021-12-02 17:55 UTC, sophiemoustard commented on src/screens/timeStamping/EventEdition/index.tsx
> +export type ModeType = 'date' | 'time';
tu peux l'importer directement du fichier DateTimeType je crois

2021-12-02 18:29 UTC, manonpalin commented on src/screens/timeStamping/EventEdition/index.tsx
> +export type ModeType = 'date' | 'time';
Oui mais en fait on en a pas besoin ici, je pense que ca vient du rebase, j'ai oublié de le retirer

2021-12-02 18:33 UTC, manonpalin commented on src/components/BottomModal/index.tsx
> +interface NiBottomModalProps {
Tu as raison, on s'était dit qu'on ne voulait garder que des types plutot que des interfaces

2021-12-03 07:50 UTC, sophiemoustard approved these changes

2021-12-03 08:16 UTC, cmolle reviewed
Il faudrait aussi modifier la methode onLeave pour prendre en compte que si l'utilisateur a modifie l'auxiliaire, on lui demande si il veut enregistrer ou non

2021-12-03 08:16 UTC, cmolle commented on src/components/EventAuxiliaryEdition/index.tsx
> +  isEditable,
Qu'est-ce qui t'a fait choisir `isEditable` plutot que `disabled` ?

2021-12-03 08:16 UTC, cmolle commented on src/screens/timeStamping/EventEdition/index.tsx
> +  ...pick(auxiliary, ['picture', 'contracts', 'identity']),
Pourquoi ce changement ?

2021-12-03 08:16 UTC, cmolle commented on src/screens/timeStamping/EventEdition/index.tsx
> +        return { ...state, auxiliary: action.payload?.auxiliary || state.auxiliary };
Il n'y a pas de valeur par defaut pour le state de SET_TIME, est-ce que tu sais si c'est voulu ? (par valeur par defaut je veux dire le fait qu'il n'y ait pas de `|| valeur` dans le cas ou `action.payload.date` n'est pas defini).

2021-12-03 08:21 UTC, manonpalin commented on src/screens/timeStamping/EventEdition/index.tsx
> +  ...pick(auxiliary, ['picture', 'contracts', 'identity']),
J'ai fait ce changement car `...pick(auxiliary, ['picture', 'contracts', 'identity.firstname', 'identity.lastname']),` ne renvoyait que les champs picture et contracts. Les champs firstname et lastname n'apparaissaient pas donc je me suis dit qu'on pouvait directement récupérer l'objet identity.

2021-12-03 08:27 UTC, manonpalin commented on src/components/EventAuxiliaryEdition/index.tsx
> +  isEditable,
A vrai dire je n'avais pas pensé a `disabled` ^^.
Je suis partie sur `isEditable` car l'action que veut faire l'utilisateur en cliquant est d'éditer l'intervenant. Dans les prochains tickets, le composant `EventEditionAuxiliary` ne sera pas vraiment disabled car meme si l'intervention est horodatée l'utilisateur pourra cliquer dessus et on renverra l'erreur `vous ne pouvez pas editer l'intervenant d'une intervention horodatée`, du coup je trouve ca bien de le nommer `isEditable`. Qu'en penses-tu?

2021-12-03 08:34 UTC, manonpalin commented on src/screens/timeStamping/EventEdition/index.tsx
> +        return { ...state, auxiliary: action.payload?.auxiliary || state.auxiliary };
Hmm c'est une bonne question. Je ne vois pas de raison pour laquelle on en mettrait pas. Que penses-tu que je l'ajoute?

2021-12-03 08:36 UTC, cmolle commented on src/components/EventAuxiliaryEdition/index.tsx
> +  isEditable,
Ok ! Je suis d'accord que comme on pourra cliquer c'est mieux isEditable, merci ! :)

2021-12-03 08:37 UTC, cmolle commented on src/screens/timeStamping/EventEdition/index.tsx
> +  ...pick(auxiliary, ['picture', 'contracts', 'identity']),
Trop bizarre 🤔 Ca ne fonctionne pas avec `pick` les champs nesté ? je crois qu'on en a ailleurs

2021-12-03 08:37 UTC, cmolle commented on src/screens/timeStamping/EventEdition/index.tsx
> +        return { ...state, auxiliary: action.payload?.auxiliary || state.auxiliary };
Ca me va :)

2021-12-03 09:25 UTC, manonpalin commented on src/screens/timeStamping/EventEdition/index.tsx
> +  ...pick(auxiliary, ['picture', 'contracts', 'identity']),
Je ne comprends pas pourquoi dans ce cas ca ne fonctionne pas...
On l'utilise ailleurs, notamment sur le répertoire formateur dans la validation on recupere les champs `identity.lastname` et `local.email` et la ca fonctionne bien

2021-12-03 09:30 UTC, manonpalin commented on src/screens/timeStamping/EventEdition/index.tsx
> +  ...pick(auxiliary, ['picture', 'contracts', 'identity']),
Plutot que de récupérer tout le champ identity, j'ai trouvé un autre moyen de récupérer les nom et prénom, qu'en penses-tu?

2021-12-03 09:57 UTC, cmolle approved these changes

2021-12-03 09:57 UTC, merged