COM-2526 - WIP
sophiemoustard/compani-outils pull request #118
Opened 2021-12-10 14:41 UTC by manonpalin

- [x] J'ai testé sur iPhone: ⚠️ j'ai un soucis d'affichage avec le clavier. lorsqu'il s'ouvre il cache la page, il faut scroll pour voir les composants, je n'arrive pas a résoudre ce probleme d'affichage (seulement sur iOS)
- [x] J'ai testé sur android

- [ ] La nouvelle version de l'app est compatible avec l'ancienne version de l'API ? (J'ai teste en me mettant sur
  master en api)
  - Oui parce que
  - Non parce que

- [ ] Je n'envoie pas de nouveau paramètre dans une route -np
    - Si j'en envoie un nouveau, explication et gestion de la compatibilite:
- [ ] J'attends un nouveau champs en retour de l'api: j'ai géré le cas où il n'y est pas -np
- [ ] J'appelle une nouvelle route: j'ai géré le cas ou la route n'existe pas. -np
- [x] Je n'ai pas changé de constante

- J'ai ajouté une variable d'environnement :
  - [ ] Je l'ai ajouté dans env.dev et env.prod aussi
  - [ ] J'ai ajouté un message sur le slite pour que la personne qui fait la MEP vérifie que son env.prod est à jour

- Cas d'usage : Depuis la page edition d'intervention, je peux ajouter et editer une note.

2021-12-13 10:28 UTC, KennyCallegari commented on src/components/form/Input/index.tsx
> +            value={value} editable={!disabled} autoCapitalize={autoCapitalize} testID={caption} multiline={multiline} />
Je trouve ça étrange d'avoir le même style pour le container + l'inputContainer + le textInput.

Pour ton ticket, on pourrait ajouter une props inputStyle pour changer la couleur du contour de `<View style={[inputStyle.inputContainer, inputStyle]}>` uniquement, qu'en penses-tu ?

2021-12-13 10:28 UTC, KennyCallegari commented on src/screens/timeStamping/EventEdition/index.tsx
>        default:
Pour reste cohérent avec `SET_AUXILIARY`, que penses-tu d'appeler cette action : 
```
case SET_MISC:
 return { ...state, misc: action.payload?.misc || '' };
```

2021-12-13 10:28 UTC, KennyCallegari commented on src/screens/timeStamping/EventEdition/index.tsx
>        default:
Ou alors refacto `SET_START` + `SET_AUXILIARY` avec `SET_FIELD`.
D'ailleurs je me demande s'il y a un intérêt à avoir ce state (misc) dans le reducer car il n'est pas utilisé par un autre composant (comme auxiliary et start) et il n'est pas dépendant d'autres states. On peut donc le passer en useState aussi. 

Qu'est-ce qui te semble le mieux ?

2021-12-13 10:28 UTC, KennyCallegari commented on src/screens/timeStamping/EventEdition/index.tsx
> +            buttonIcon={<MaterialIcons name={'playlist-add'} size={24} color={COPPER[600]} />}
On peut demander à Romain si ce composant a par défaut cet icon, ce qui permettrait de directement le mettre dans le composant EventFieldEdition. Qu'en penses-tu ?

2021-12-13 10:28 UTC, KennyCallegari commented on src/screens/timeStamping/EventEdition/styles.ts
> +  keyboardAvoidingView: {
à mettre au dessus de container (pour conserver l'ordre des styles

2021-12-13 10:28 UTC, KennyCallegari commented on src/screens/timeStamping/EventEdition/styles.ts
> +  keyboardAvoidingView: {
Tu peux supprimer    `backgroundColor: COPPER_GREY[50],` non ?

2021-12-13 16:56 UTC, manonpalin commented on src/components/EventFieldEdition/styles.ts
> +    paddingHorizontal: PADDING.SM,
En fait je l'ai ajouté car sinon lorsque l'on sélectionne l'input, la 'surbrillance' du bord est coupée par le padding du container

2021-12-13 17:03 UTC, KennyCallegari commented on src/components/EventFieldEdition/index.tsx
> +      </TouchableOpacity>}
pardon 😄 Il faut ajouter une tabulation sur ce paragraphe car il n'est pas bien formatté : 
```
     {!displayText && !disabled &&
        <TouchableOpacity style={styles.textContainer} onPress={() => setDisplayText(true)} >
          {buttonIcon}
          <Text style={styles.text}>{buttonTitle}</Text>
        </TouchableOpacity>}
```

2021-12-13 17:11 UTC, manonpalin commented on src/components/EventFieldEdition/styles.ts
> +    padding: PADDING.MD,
Oui bien vu ! J'ajoute ca

2021-12-13 17:25 UTC, manonpalin commented on src/screens/timeStamping/EventEdition/index.tsx
> +            buttonIcon={<MaterialIcons name={'playlist-add'} size={24} color={COPPER[600]} />}
L'idee est de réutiliser ce composant dans le prochain ticket pour l'ajout du champ déplacement vehiculé, du coup je ne vois pas trop l'intérêt d'ajouter cet icône par défaut. Qu'en penses-tu?

2021-12-13 17:28 UTC, manonpalin commented on src/screens/timeStamping/EventEdition/styles.ts
> +  keyboardAvoidingView: {
Oui bien vu !

2021-12-13 17:42 UTC, manonpalin commented on src/screens/timeStamping/EventEdition/index.tsx
>        default:
En écrivant la stratégie technique on a un peu anticipé le ticket suivant en pensant a ce qui pourra être réutilisé par la suite. C'est pour ca qu'on a créé cette action assez généraliste. (qui sera aussi utilisée pour mettre a jour le nombre de km parcouru avec le beneficiaire)
Pour la gestion des States, j'ai l'impression que c'est plus clair si on a tout dans le reducer,  que penses-tu  de mutualiser avec SET_AUXILIARY ? C'est a dire de ne créer une seule action SET_FIELD pour mettre a jour auxiliary et misc ( et par la suite kmDuringEvent) ? 
Pour mutualiser avec SET_START, je n'ai pas l'impression qu'on puisse car je ne vois pas comment definir la valeur par défaut a false

2021-12-14 07:17 UTC, manonpalin commented on src/components/EventFieldEdition/index.tsx
> +      </TouchableOpacity>}
Ahhhh dacc, merci pour la précision :)

2021-12-14 11:05 UTC, KennyCallegari commented on src/screens/timeStamping/EventEdition/index.tsx
>        default:
On n'a pas tranché sur une bonne pratique là dessus. Personnellement j'aime bien 2 bonnes pratiques sur lesquelles je ne tranche pas :
- avoir un reducer qui ne correspond qu'à un seul groupe d'état (ici un reducer pour `event`, donc `misc` aurait sa place dans ce reducer)
- avoir un reducer uniquement pour les champs qui sont liés (histories + startDateTimeStamp + endDateTimeStamp et startDate + endDate) et là `misc`, `auxiliary` n'auraient pas leur place. Et `start` non plus d'ailleurs

J'aime bien l'idée de `SET_FIELD` avec un reducer pour `event`. Donc on peut l'utiliser pour `misc` et faire le refacto pour `auxiliary` et `start`. Je ne comprends pas le problème pour définir la valeur par défaut, il y a `l'initialState` pour ça et `eventDispatch({ type: SET_FIELD, payload: { start: value || false } })`.

2021-12-14 11:11 UTC, KennyCallegari commented on src/screens/timeStamping/EventEdition/index.tsx
>        default:
Il faudrait ajouter `misc: ''` à `initialState` aussi

2021-12-14 11:25 UTC, KennyCallegari commented on src/components/EventFieldEdition/styles.ts
> +    paddingHorizontal: PADDING.SM,
je peux le supprimer sans conséquence perso 🤔

2021-12-14 11:55 UTC, manonpalin commented on src/components/EventFieldEdition/styles.ts
> +    paddingHorizontal: PADDING.SM,
<img width="309" alt="Capture d’écran 2021-12-14 à 12 53 41" src="https://user-images.githubusercontent.com/81675019/145993579-241cb7fc-4747-4093-8639-1bccb0ba973d.png">
Sur android l'affichage est coupé si je n'ajoute pas cette marge

2021-12-14 12:01 UTC, sophiemoustard commented on src/screens/timeStamping/EventEdition/index.tsx
>        default:
par rapport a ta distinction Kenny, je pense que les 2 peuvent avoir une utilité et peuvent être simplifié en "regrouper les éléments qui vont ensemble" (soit parce qu'il ont une cohérence fonctionnel qui justifie ce regroupement technique, soit parce qu'ils ont un impact les uns sur les autres)
Dnas notre cas, l'utilisation d'un reducer permet de simplifier la gestion d'état du composant :)

2021-12-14 12:59 UTC, sophiemoustard requested changes

2021-12-14 12:59 UTC, sophiemoustard commented on src/screens/timeStamping/EventEdition/index.tsx
> +        { auxiliary: event.auxiliary._id, ...pick(event, ['startDate', 'endDate', 'misc']) }
que penses tu de definir une constante `pickedFileds` car la liste va s'allonger au fur et a mesure des PRs et du coup d'avoir `await Events.updateById(event._id, { auxiliary: event.auxiliary._id, ...pick(event, pickedFileds) });` ?

2021-12-14 13:45 UTC, manonpalin commented on src/screens/timeStamping/EventEdition/index.tsx
>        default:
Ok du coup dans notre cas pour rester dans la logique de simplifier la gestion d'états, on peut regrouper SET_AUXILIARY, SET_START et SET_FIELD en une seule action du reducer :)

2021-12-14 13:54 UTC, manonpalin commented on src/screens/timeStamping/EventEdition/index.tsx
> +        { auxiliary: event.auxiliary._id, ...pick(event, ['startDate', 'endDate', 'misc']) }
oui bonne idee

2021-12-14 14:48 UTC, sophiemoustard commented on src/components/EventFieldEdition/styles.ts
> +    paddingHorizontal: PADDING.SM,
j'ai l'impression de voir l'impact de ce padding : est ce bien l'espace entre la bordure de l'input et le texte "Ciyrdvh.." qui augmente ?
mais je ne comprends pas pourquoi on veut un espacement specifique pour cet input par rapport aux autres ?

2021-12-14 14:50 UTC, sophiemoustard commented on src/components/EventFieldEdition/styles.ts
> +    paddingHorizontal: PADDING.SM,
et idem pour la bordure, je pense que ca vaut le coup de confirmer avec Romain qu'il vaut une bordure specifique pour ces champs, differente de celle dans le formulaire d'edition du profil de la personne connectée

2021-12-14 14:52 UTC, sophiemoustard commented on src/components/EventFieldEdition/styles.ts
> +    paddingHorizontal: PADDING.SM,
et on pourrait mettre `COPPER_GREY[200]` pour que ce soit homogene avec la bordure des autres elements de la page, qu'en penses tu ? a confirmer avec ROmain peut etre

2021-12-14 16:44 UTC, manonpalin commented on src/components/EventFieldEdition/styles.ts
> +    paddingHorizontal: PADDING.SM,
Oui on peut retirer ce padding, il ne sert a rien !

J'en ai discuté avec Romain et il est d'accord avec l'idée de modifier le style de l'input en: modifiant la couleur de la bordure `COPPER_GREY[300]` au lieu de `COPPER_GREY[600]` si l'input n'est pas selectionné

2021-12-15 08:27 UTC, sophiemoustard approved these changes

2021-12-15 08:31 UTC, KennyCallegari approved these changes

2021-12-15 08:34 UTC, merged