Com 2609
sophiemoustard/compani-outils pull request #133
Opened 2022-01-26 15:41 UTC by manonpalin

- [x] J'ai testé sur iphone
- [x] J'ai testé sur android

- [] La nouvelle version de l'app est compatible avec l'ancienne version de l'API ? (J'ai teste en me mettant sur
  master en api)
  - Oui parce que
  - Non parce que

- [x] Je n'envoie pas de nouveau paramètre dans une route
    - Si j'en envoie un nouveau, explication et gestion de la compatibilite:
- [ ] J'attends un nouveau champs en retour de l'api: j'ai géré le cas où il n'y est pas -np
- [ ] J'appelle une nouvelle route: j'ai géré le cas ou la route n'existe pas. -np
- [x] Je n'ai pas changé de constante

- J'ai ajouté une variable d'environnement : -np 
  - [ ] Je l'ai ajouté dans env.dev et env.prod aussi
  - [ ] J'ai ajouté un message sur le slite pour que la personne qui fait la MEP vérifie que son env.prod est à jour

- Cas d'usage : Depuis la page édition d'une intervention je peux accéder a la fiche beneficiaire

2022-01-27 10:16 UTC, CorentinMartinot approved these changes

2022-01-27 15:16 UTC, sophiemoustard commented on src/screens/timeStamping/EventEdition/styles.ts
> +  customerProfileButtonTitle: {
ici la police me parait tres petite, je pense que tu peux mettre `...FIRA_SANS_REGULAR.MD` pour agrandir

2022-01-27 16:40 UTC, manonpalin commented on src/screens/timeStamping/EventEdition/styles.ts
> +  customerProfileButtonTitle: {
Oui tu as raison, c'est mieux avec une police plus grande :)

2022-01-28 08:19 UTC, sophiemoustard requested changes

2022-01-28 08:19 UTC, sophiemoustard commented on src/components/Header/index.tsx
> +  iconColor: string,
tu pourrais mettre ces 3 propriétés avec les valeurs par defaut `arrow-left` / `icon.MD` / `COPPER[500]` - dans tes 2 occurences ce sont les memes valeurs et on pourrait imaginer d'autres pages avec ces valeurs la également
En travaillant avec des propriétés apr defaut tu gardes la souplesse de les changer si besoin et tu simplifies le code partout ou c'est la cas general :)

2022-01-28 09:16 UTC, manonpalin commented on src/components/Header/index.tsx
> +  iconColor: string,
Bien vu, c'est fait :)

2022-01-28 10:01 UTC, sophiemoustard approved these changes

2022-01-28 10:01 UTC, merged