Com 2610
sophiemoustard/compani-outils pull request #135
Opened 2022-01-31 10:22 UTC by manonpalin

- [ ] J'ai testé sur iphone
- [ ] J'ai testé sur android

- [ ] La nouvelle version de l'app est compatible avec l'ancienne version de l'API ? (J'ai teste en me mettant sur
  master en api)
  - Oui parce que
  - Non parce que

- [ ] Je n'envoie pas de nouveau paramètre dans une route
    - Si j'en envoie un nouveau, explication et gestion de la compatibilite:
- [ ] J'attends un nouveau champs en retour de l'api: j'ai géré le cas où il n'y est pas
- [ ] J'appelle une nouvelle route: j'ai géré le cas ou la route n'existe pas.
- [ ] Je n'ai pas changé de constante

- J'ai ajouté une variable d'environnement :
  - [ ] Je l'ai ajouté dans env.dev et env.prod aussi
  - [ ] J'ai ajouté un message sur le slite pour que la personne qui fait la MEP vérifie que son env.prod est à jour

- Cas d'usage : ETQ Auxiliaire sur la fiche bénéficiaire, j'ai accès a l'environnement du bénéficiaire.

2022-01-31 13:22 UTC, KennyCallegari commented on src/screens/CustomerProfile/index.tsx
> +          { !loading &&
pas d'espace ici

2022-01-31 13:22 UTC, KennyCallegari commented on src/screens/CustomerProfile/index.tsx
> +          <ErrorMessage message={apiErrorMessage || ''}/>
un espace avant `/>`

2022-01-31 13:22 UTC, KennyCallegari commented on src/screens/CustomerProfile/index.tsx
> +  const [apiErrorMessage, setApiErrorMessage] = useState<string>('');
Tu pourrais ajouter ce composant dans la liste des composants à refacto dans le ticket JIRA ? https://compani.atlassian.net/browse/COM-2626?atlOrigin=eyJpIjoiN2M4ODNiNWQ1NDMyNGE0Njg3NzIxZDk2NzFhMWEyYWYiLCJwIjoiaiJ9

2022-01-31 13:22 UTC, KennyCallegari commented on src/screens/CustomerProfile/index.tsx
> +          { !loading &&
D'ailleurs est-ce qu'on a besoin de ne pas afficher l'input si la page charge ? Car le bouton enregistrer n'est déjà pas disponible et ça créé un visuel pas très satisfaisant je trouve. Qu'en penses-tu ?

On pourrait aussi utiliser la props `disabled`

2022-01-31 13:34 UTC, manonpalin commented on src/screens/CustomerProfile/index.tsx
> +  const [editedFollowUp, setEditedFollowUp] = useState<UserType['followUp']>({ environment: '' });
Si on le met dans une constante, typeScript le considère comme étant une valeur et non plus un type, il faudrait donc l'écrire : `useState<UserType[typeof FOLLOW_UP]=...`. 
Je trouve que ça alourdit beaucoup la notation. Ailleurs dans le code on a aussi utilisé la notation que j'ai utilisé. Que penses-tu de rester sur celle-ci?

2022-01-31 13:35 UTC, manonpalin commented on src/screens/CustomerProfile/index.tsx
> +    else setExitModal(true);
Yes je prepare pour la suite car dans le ticket qui suit on va aussi ajouter le champs `objectives`

2022-01-31 13:44 UTC, manonpalin commented on src/screens/CustomerProfile/index.tsx
> +          { !loading &&
Au départ je ne l'avais pas mis sauf que le composant s'affiche avec ses valeurs initiales le temps que tous les états se mettent a jour et l'affichage de l'input se fait en deux temps: 
- premier affichage où il affiche le placeholder et le nom n'apparait pas
- deuxième affichage ou il a récupéré des infos du back et affiche le contenu

Pour régler ce problème, je trouvais bien de n'afficher le contenu que lorsque le chargement des infos est terminé.

2022-01-31 13:56 UTC, KennyCallegari commented on src/screens/CustomerProfile/index.tsx
> +  const [editedFollowUp, setEditedFollowUp] = useState<UserType['followUp']>({ environment: '' });
effectivement :/ Gardons comme ça

2022-01-31 13:58 UTC, KennyCallegari commented on src/screens/CustomerProfile/index.tsx
> +          { !loading &&
Dans ce cas que penses-tu d'afficher un loader sur la page le temps qu'on récupère toutes les infos ? Ce qui évitera le soucis pour les prochains composants de cette page aussi

2022-01-31 14:29 UTC, manonpalin commented on src/screens/CustomerProfile/index.tsx
> +          { !loading &&
Yes on peut faire ca, mais dans ce cas penses-tu que la gestion des loader du bouton et de la page se font avec un seul état ou est-ce qu'il vaut mieux creer deux états différents? Je n'ai pas reussi a trancher ^^

2022-01-31 14:54 UTC, KennyCallegari commented on src/screens/CustomerProfile/index.tsx
> +          { !loading &&
ça ne me choque pas avec un seul. On peut demander à Romain ?

2022-02-01 08:17 UTC, sophiemoustard requested changes

2022-02-01 08:17 UTC, sophiemoustard commented on src/screens/CustomerProfile/index.tsx
> +  const initialCustomerFollowUp = useRef<UserType['followUp']>(editedFollowUp);
pourquoi avoir une ref ? et un doublon avec ce qu'il y a dans la variable d'etat `customer`

2022-02-01 08:17 UTC, sophiemoustard commented on src/screens/CustomerProfile/index.tsx
> +  const [editedFollowUp, setEditedFollowUp] = useState<UserType['followUp']>({ environment: '' });
pourquoi ne pas avoir defini une variable `editedCustomer` pour anticiper les futurs changements ?

2022-02-01 08:17 UTC, sophiemoustard commented on src/screens/CustomerProfile/index.tsx
> +    if (isEqual(pick(editedFollowUp, ['environment']), pick(initialCustomerFollowUp.current, ['environment']))) {
tu pourrais mutualiser `['environment']` dans une variable `pickedFields` par exemple pour anticiper les modif des futurs champs a venir

2022-02-01 08:17 UTC, sophiemoustard commented on src/screens/CustomerProfile/index.tsx
> +      setApiErrorMessage('Une erreur s\'est produite, si le problème persiste, contactez le support technique.');
il n'y a que cette erreur qui peut arriver du back ?

2022-02-01 08:17 UTC, sophiemoustard commented on src/screens/timeStamping/EventEdition/index.tsx
> +  const initialEvent = useRef<EventEditionStateType>(initialState);
pourquoi cet ajout ? j'ai l'impression qu'on duplique l'info

2022-02-01 13:02 UTC, manonpalin commented on src/screens/CustomerProfile/index.tsx
> +    if (isEqual(pick(editedFollowUp, ['environment']), pick(initialCustomerFollowUp.current, ['environment']))) {
C'est fait

2022-02-01 13:02 UTC, manonpalin commented on src/screens/CustomerProfile/index.tsx
> +  const [editedFollowUp, setEditedFollowUp] = useState<UserType['followUp']>({ environment: '' });
Oui tu as raison, j'étais focalisée sur le suivi mais autant definir `editedCustomer`

2022-02-01 13:17 UTC, manonpalin commented on src/screens/CustomerProfile/index.tsx
> +  const initialCustomerFollowUp = useRef<UserType['followUp']>(editedFollowUp);
Tu as raison pas besoin de cette ref, on a deja l'info dans `customer`

2022-02-01 13:22 UTC, manonpalin commented on src/screens/CustomerProfile/index.tsx
> +  const initialCustomerFollowUp = useRef<UserType['followUp']>(editedFollowUp);
J'ai retravaillé cette partie en ne définissant que deux variables d'états:
- `initialCustomer` correspondant aux infos initiales du beneficiaire (sans modifications)
- `editedCustomer` correspond aux infos du beneficiaire apres modifications 

Pour que la methode `onLeave` fonctionne bien, je ne vois pas d'autre moyen que de creer ces deux variables d'état. Qu'en penses-tu?

2022-02-01 13:50 UTC, manonpalin commented on src/screens/timeStamping/EventEdition/index.tsx
> +  const initialEvent = useRef<EventEditionStateType>(initialState);
J'étais partie sur la meme logique que dans `CustomerProfile` mais pas besoin de cet ajout tu as raison :)

2022-02-01 14:09 UTC, manonpalin commented on src/screens/CustomerProfile/index.tsx
> +      setApiErrorMessage('Une erreur s\'est produite, si le problème persiste, contactez le support technique.');
On peut recevoir une 403 si le beneficiaire que l'on veut mettre a jour n'existe pas, je trouve que c'est pas mal d'afficher ce message si cette erreur est renvoyé du back. Qu'en penses-tu?

2022-02-01 14:38 UTC, sophiemoustard requested changes

2022-02-01 15:03 UTC, manonpalin commented on src/screens/timeStamping/EventEdition/index.tsx
> +        setInitialState(editedEvent);
Je ne suis pas sure que ce soit utile dans ce cas la car les formats de startDate et endDate sont déjà des CompaniDate().toISO(), je pense que dans ce cas `setInitialState(editedEvent);` est strictement équivalent a  `setInitialState({
          ...editedEvent,
          startDate: CompaniDate(editedEvent.startDate).toISO(),
          endDate: CompaniDate(editedEvent.endDate).toISO(),
        });`
non ? :)

2022-02-01 16:59 UTC, sophiemoustard approved these changes

2022-02-01 17:00 UTC, merged