COM-3547: wip
sophiemoustard/compani-outils pull request #197
Opened 2023-09-08 09:45 UTC by ulysseferreira

### TESTS  :computer:

- J'ai testé sur iphone : 
  - [ ] simulateur
  - [ ] physique
- J'ai testé sur android :
  - [ ] simulateur
  - [x] physique
- [ ] J'ai testé sur tablette

---

### POINTS D'ATTENTION POUR CETTE PR  :warning:

- [x] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [Doc de déploiement](https://www.notion.so/D-ploiement-et-distribution-mobile-7d25b02c0de448e2af7100151401d7e2) ce qu'il fallait mettre à jour
- [ ] Mes changements entrainent une incompatibilité avec l'ancienne version de l'api
  - [ ] Si oui, j'ai noté dans le [Doc de déploiement](https://www.notion.so/D-ploiement-et-distribution-mobile-7d25b02c0de448e2af7100151401d7e2) qu'il faut fusionner l'api dans staging avant d'envoyer le build

_Si tu as lu cette description, pense à réagir avec un :eye:_

2023-09-08 09:52 UTC, ulysseferreira commented on __tests__/authentication.test.js
les tests passent mais il y a une 404 sur l'appel à getEvents comme si le mock ne se faisait pas bien et que l'appel était vraiment envoyé, je ne comprend pas trop pourquoi

2023-09-08 14:53 UTC, sophiemoustard requested changes

2023-09-08 14:53 UTC, sophiemoustard commented on app.config.js
> +      versionCode: 22,
tu as changé le `buildNumber` pour ios mais pas le `versionCode` pour Android

2023-09-08 14:53 UTC, sophiemoustard commented on app.config.js
> +      return 'Compani Outils';
le format n'est pas le bon ; c'est etrange de retourner parfois une objet et parfois un string non ?

2023-09-08 14:53 UTC, sophiemoustard commented on eas.json
> +}
il manque une ligne a la fin de ton fichier

2023-09-08 14:53 UTC, sophiemoustard commented on environment.ts
> +   * Il faudra l'enlever quand on aura totalement migrer vers EAS build
EAS updates non ?

2023-09-08 14:53 UTC, sophiemoustard commented on __tests__/authentication.test.js
le souci viens de la ligne `{ params: { auxiliary: 'userId', startDate, endDate, type: INTERVENTION, isCancelled: false } }` ; elle n'est peut etre aps bien configurée

2023-09-08 15:12 UTC, ulysseferreira commented on app.config.js
> +      return 'Compani Outils';
j'ai mis le nom de l'app qui est sur le Store, pour toi il faudrait mettre quoi ?

2023-09-08 15:12 UTC, ulysseferreira commented on eas.json
> +}
done

2023-09-08 15:13 UTC, ulysseferreira commented on environment.ts
> +   * Il faudra l'enlever quand on aura totalement migrer vers EAS build
j'ai repris tel quel ce qui était dans formation, c'est une erreur dans Formation ou alors on a fini de migrer et ça peut être retiré ?

2023-09-08 15:17 UTC, ulysseferreira commented on app.config.js
> +      versionCode: 22,
je passe à 30 comme préconisé sur le doc de MEP ?

2023-09-08 15:19 UTC, ulysseferreira commented on eas.json
> +}
(côté formation il manque aussi, tu pourrais le rajouter dans ta pr)

2023-09-11 09:26 UTC, sophiemoustard commented on app.config.js
> +      versionCode: 22,
qu'en penses tu ?

2023-09-11 09:27 UTC, sophiemoustard commented on app.config.js
> +      return 'Compani Outils';
le retour de ta methode doit etre consistant : si elle retourne un objet, il faut que ton retour par defaut soit un objet aussi, sinon ca va créer des erreurs

2023-09-11 09:27 UTC, sophiemoustard commented on eas.json
> +}
yes

2023-09-11 09:29 UTC, sophiemoustard commented on environment.ts
> +   * Il faudra l'enlever quand on aura totalement migrer vers EAS build
tu peux prendre un peu de recul par rapport a ce qui est fait coté formation, comprendre ce que tu fais et adapter si tu penses que c'est necessaire ; tu peux aussi poser des questions si tu n'es pas sur ou si tu as un doute.
je te laisse creuser ce point et voir a quelle conlusion ca te mène.
Faire cs changement sur Compani Outil peut te permnettre d'améliorer aussi Compani Formation

2023-09-11 09:31 UTC, sophiemoustard commented on __tests__/authentication.test.js
@ulysseferreira c'est toi ou moi qui a repondu ca ?
> j'ai l'impression que tous les paramètres sont acceptés par la route mais en effet en retirant type et isCancelled ça fonctionne mieux
je n'ai pas le souvenir d'avoir mis la seconde partie mais l'affichage github le dit 🤔

2023-09-11 12:29 UTC, ulysseferreira commented on app.config.js
> +      return 'Compani Outils';
dans ce cas il faut corriger sur Formation aussi car c'est comme ça qu'on fait

2023-09-11 12:43 UTC, sophiemoustard commented on eas.json
> +}
chez moi il y a bine une ligne a la fun du fichier `eas.json` cote formation...

2023-09-11 13:35 UTC, ulysseferreira commented on __tests__/authentication.test.js
non en effet c'est moi qui l'ai écrit

2023-09-11 13:35 UTC, ulysseferreira commented on app.config.js
> +      versionCode: 22,
par cohérence avec Formation je dirais que oui

2023-09-11 13:45 UTC, ulysseferreira commented on app.config.js
> +      return 'Compani Outils';
on veut mettre quoi par défaut ? local ?

2023-09-12 15:26 UTC, sophiemoustard commented on app.config.js
> +      versionCode: 22,
je suis d'accord

2023-09-12 15:29 UTC, sophiemoustard commented on app.config.js
> +      return 'Compani Outils';
cf mon premier commentaire, je challenge ici le **format** du retour : tu mets une chaine de caractère alors que dasn tous les autres cas, tu mets une objet avec 2 clés `appName` et `bundleIdentifier`
il faut donc ici que tu retournes un objet

2023-09-12 15:36 UTC, sophiemoustard commented
As tu testé l'ajout de "EXPO_USE_SOURCE" pour faire fonctionner le build ios ?

2023-09-12 17:41 UTC, ulysseferreira commented on app.config.js
> +      return 'Compani Outils';
oui j'ai bien compris mais l'objet par défaut ça doit être un des cas précédents, on va pas en inventer un 4e donc je demande lequel on choisi parmis local, development ou production pour être mis dans default à la place de la string

2023-09-13 07:35 UTC, sophiemoustard commented on app.config.js
> +      return 'Compani Outils';
et dans ce cas, tu peux formater comme suit : 
```
case DEVELOPMENT:
    return { appName: 'Compani Outils - Dev', bundleIdentifier: 'com.compani.erp.dev' };
  case PRODUCTION:
    return { appName: 'Compani Outils', bundleIdentifier: 'com.compani.erp' };
  case LOCAL:
  default:
    return { appName: 'Compani Outils - local', bundleIdentifier: 'com.compani.erp.local' };
```

2023-09-13 07:38 UTC, sophiemoustard commented on environment.ts
> +   * Il faudra l'enlever quand on aura totalement migrer vers EAS build
en remontant dans le code de compani formation : https://compani.atlassian.net/browse/COM-2965 tu vois que cette section a ete ajouté pour expo-publish et est donc necessaire tant qu'on n'a pas migré vers eas updates

2023-09-13 09:11 UTC, ulysseferreira commented on app.config.js
> +      return 'Compani Outils';
yes

2023-09-13 09:21 UTC, ulysseferreira commented on environment.ts
> +   * Il faudra l'enlever quand on aura totalement migrer vers EAS build
dans le build app.config.js et eas.json sont fusionné pour former manifest ? quand on appelle Constants.manifest c'est ça que ça fait ? parce que Constants.manifest.extra est dans app.config et Constants.manifest.releaseChannel est dans eas.json

2023-09-13 09:31 UTC, ulysseferreira commented on eas.json
> +    },
done

2023-09-13 09:33 UTC, ulysseferreira commented on eas.json
> +    "dev": {
done

2023-09-13 09:33 UTC, ulysseferreira commented on eas.json
done

2023-09-13 09:33 UTC, ulysseferreira commented on eas.json
> +    "dev-simulator": {
done

2023-09-13 14:04 UTC, sophiemoustard approved these changes

2023-09-14 08:22 UTC, manonpalin commented on .gitignore
>  env/*
Tu peux retirer ce dossier non ?

2023-09-14 08:26 UTC, manonpalin commented on app.config.js
> +    slug: 'erp-mobile',
Pourquoi c'est pas compani-outils ici plutot?

2023-09-14 08:30 UTC, manonpalin commented on app.config.js
> +        NSCameraUsageDescription: 'Autorisez l\'accès à votre caméra pour pouvoir prendre une photo et la charger comme photo de profil dans Compani et scanner le QR code.',
Cote outils on ne peut pas charger de photo de profil, tu pourrais simplifier en : 'Autorisez l\'accès à votre caméra pour pouvoir scanner le QR code.'

Et du coup je pense qu'on a pas besoin de definir `NSPhotoLibraryUsageDescription` en dessous si ?

2023-09-14 08:46 UTC, ulysseferreira commented on eas.json
> +  "submit": {
c'est créé par défaut à la configuration de eas, qu'est-ce-qui te fait dire qu'il faudrait le retirer ?

2023-09-14 08:48 UTC, ulysseferreira commented on .gitignore
>  env/*
yes, il faut être sûr que vous l'ayez bien supprimer de votre projet par contre sinon ça risque de l'uploader

2023-09-14 08:49 UTC, ulysseferreira commented on app.config.js
> +    slug: 'erp-mobile',
j'ai repris ce qu'on avait dans le app.json avant

2023-09-14 08:52 UTC, ulysseferreira commented on app.config.js
> +        NSCameraUsageDescription: 'Autorisez l\'accès à votre caméra pour pouvoir prendre une photo et la charger comme photo de profil dans Compani et scanner le QR code.',
bien vu

2023-09-14 08:52 UTC, ulysseferreira commented on app.config.js
> +      permissions: ['CAMERA', 'READ_EXTERNAL_STORAGE', 'WRITE_EXTERNAL_STORAGE'],
ni le read_external_storage

2023-09-14 10:24 UTC, manonpalin commented on app.config.js
> +    slug: 'erp-mobile',
Hmm ok mais je pense qu'on pourrait le changer pour etre coherent avec formation. 

Je pense que c'est faisable. Globalement le slug est utilisé dans l'url `https://expo.dev/@sophiemoustard/erp-mobile?serviceType=classic&distribution=expo-go&release-channel=dev` 

Je trouve plus coherent de le nommer `compani-outils` qui correspond au nom du projet

2023-09-14 13:17 UTC, manonpalin commented on app.config.js
> +    slug: 'erp-mobile',
ok

2023-09-14 13:21 UTC, manonpalin commented on eas.json
> +  "submit": {
Je sais pas trop, c'est un objet vide dans production. Du coup je me demandais si c'etait necesssaire mais laissons comme ca

2023-09-14 13:55 UTC, merged